version: '3.8'

services:
  db:
    image: postgres:15
    container_name: articulo65_db_prod
    environment:
      POSTGRES_DB: repositorio_articulo65
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - articulo65_network

  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: articulo65_web_prod
    environment:
      - DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-django-insecure-change-me}
      - DB_NAME=repositorio_articulo65
      - DB_USER=postgres
      - DB_PASSWORD=${DB_PASSWORD:-postgres123}
      - DB_HOST=db
      - DB_PORT=5432
    volumes:
      - media_files:/app/media
      - static_files:/app/staticfiles
    ports:
      - "80:8000"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - articulo65_network

  nginx:
    image: nginx:alpine
    container_name: articulo65_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files:/app/staticfiles:ro
      - media_files:/app/media:ro
    ports:
      - "3018:80"
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - articulo65_network

volumes:
  postgres_data:
  media_files:
  static_files:

networks:
  articulo65_network:
    driver: bridge