# Generated by Django 5.2.1 on 2025-07-15 17:40

import archivos.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fraccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_usuario_asignado', models.CharField(choices=[('transparencia', 'Unidad de Transparencia'), ('recursos_financieros', 'Unidad de Recursos Financieros')], max_length=20, verbose_name='Tipo de Usuario Asignado')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fracción',
                'verbose_name_plural': 'Fracciones',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_periodo', models.CharField(choices=[('anual', 'Anual'), ('trimestral', 'Trimestral'), ('bimestral', 'Bimestral')], max_length=15, verbose_name='Tipo de Periodo')),
                ('año', models.IntegerField(verbose_name='Año')),
                ('periodo_especifico', models.CharField(help_text='Ej: T1, T2, B1, etc.', max_length=20, verbose_name='Periodo Específico')),
                ('archivo', models.FileField(upload_to=archivos.models.archivo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre Original')),
                ('tamaño', models.BigIntegerField(verbose_name='Tamaño (bytes)')),
                ('vigente', models.BooleanField(default=True, verbose_name='Vigente')),
                ('version', models.IntegerField(default=1, verbose_name='Versión')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('fraccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.fraccion', verbose_name='Fracción')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Acceso')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archivos.archivo', verbose_name='Archivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Acceso',
                'verbose_name_plural': 'Historial de Accesos',
                'ordering': ['-fecha_acceso'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('transparencia', 'Unidad de Transparencia'), ('recursos_financieros', 'Unidad de Recursos Financieros')], max_length=20, verbose_name='Tipo de Usuario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['fraccion', 'año', 'periodo_especifico'], name='archivos_ar_fraccio_290644_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['vigente'], name='archivos_ar_vigente_b72d8b_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['created_at'], name='archivos_ar_created_ce3ec6_idx'),
        ),
    ]
