# Generated by Django 5.2.1 on 2025-07-15 22:04

import archivos.models
import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(max_length=500, upload_to=archivos.models.archivo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])], verbose_name='Archivo'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nombre_original',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre Original'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='tamaño',
            field=models.BigIntegerField(default=0, verbose_name='Tamaño (bytes)'),
        ),
        migrations.AlterField(
            model_name='historialacceso',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
        migrations.AddConstraint(
            model_name='archivo',
            constraint=models.UniqueConstraint(fields=('fraccion', 'año', 'periodo_especifico', 'version'), name='unique_archivo_version'),
        ),
    ]
