# Generated by Django 5.2.1 on 2025-09-01 17:34

import archivos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='editada',
            field=models.BooleanField(default=False, verbose_name='Editada'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(max_length=500, upload_to=archivos.models.archivo_upload_path, verbose_name='Archivo'),
        ),
    ]
