# Generated by Django 5.2.1 on 2025-07-16 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_alter_archivo_archivo_alter_archivo_nombre_original_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historialacceso',
            name='es_acceso_publico',
            field=models.BooleanField(default=False, verbose_name='Acceso Público'),
        ),
        migrations.AddField(
            model_name='historialacceso',
            name='user_agent',
            field=models.TextField(blank=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='historialacceso',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='historialacceso',
            index=models.Index(fields=['fecha_acceso'], name='archivos_hi_fecha_a_3e2566_idx'),
        ),
        migrations.AddIndex(
            model_name='historialacceso',
            index=models.Index(fields=['es_acceso_publico'], name='archivos_hi_es_acce_6e5215_idx'),
        ),
        migrations.AddIndex(
            model_name='historialacceso',
            index=models.Index(fields=['archivo', 'fecha_acceso'], name='archivos_hi_archivo_38925f_idx'),
        ),
    ]
